spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션 실행 시점에 갖고 있는 entity를 다지우고 다시 생성
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
   # open-in-view: false # OSIV Disable 설정 (False로 하게되면 영속성 컨텍스트가 Service단에서 종료됨.)

logging:
  level:
    org.hibernate.SQL: debug